# Introduction To Large Language Model (LLM) and Natural Language Processing (NLP)

### Understanding Natural Language Processing (NLP)
Natural Language Processing is a branch of AI that focuses on the interaction between computers and humans through natural language. The goal of NLP is to enable computers to understand, interpret, and produce human language in a way that is both meaningful and useful. NLP combines computational linguistics—rule-based modeling of human language—with statistical, machine learning, and deep learning models. These techniques enable the handling of various language-based tasks such as translation, sentiment analysis, and topic segmentation.

### Understanding Large Language Models (LLMs)
Large Language Models (LLMs) like GPT (Generative Pre-trained Transformer) and BERT (Bidirectional Encoder Representations from Transformers) are advanced architectures used in NLP. These models are trained on vast amounts of text data and use the learned patterns to generate text that is coherent, contextually relevant, and often indistinguishable from text written by humans. LLMs utilize the transformer architecture, which is notable for its reliance on self-attention mechanisms to process words in relation to all other words in a sentence, thereby improving the understanding of context.

### Key Differences Between NLP and LLM
    1. Scope and Application
        NLP: Encompasses a broad range of techniques and tools designed to solve language-based tasks. This includes speech recognition, language translation, and sentiment analysis.
        LLM: Primarily focuses on generating and understanding text based on the training it has received from large datasets. It is a subset of the broader NLP field.
    2. Technological Complexity
        NLP: Can be implemented using simpler models such as decision trees and linear regression when the tasks are relatively straightforward.
        LLM: Relies on complex, deep learning models that require significant computational power and data, making them more suited for tasks that require a deep understanding of language.
    3. Training Data
        NLP: The size and quality of the training dataset can vary significantly based on the specific application or task.
        LLM: Requires massive amounts of training data to learn effectively. These models often train on datasets encompassing a broad range of internet text.
    4. Real-World Application
        NLP: Used in practical applications that require interaction with humans in natural language, such as chatbots, virtual assistants, and customer service automation.
        LLM: While also used in similar applications, LLMs excel in tasks that require generating human-like text, such as writing articles, composing poetry, or creating conversational AI responses.

### Future Trends: Predicting the Convergence of NLP vs LLM
The combination of NLP and LLM is expected to create new opportunities and uses. This partnership may improve our lives by influencing how we interact with AI.

    Enhanced AI Assistants: More sophisticated and contextually aware AI assistants could result from the integration. They'll be able to comprehend and react to intricate human exchanges.
    Advances in Content Creation by Automation: We should anticipate increasingly advanced tools for producing information in a variety of formats. They will combine the creative powers of LLM with the language rules of NLP.
    Enhanced Robotics Language Understanding: This synergy may improve robotics' capacity for language processing. More organic and efficient human-robot interactions result from it.

# Example 1: Building a Large Language Model from Scratch

Large Language Models (LLMs) are the backbone of modern AI applications, from chatbots to code generators. But how are large language models built?
Modern language models (like GPT-4) use transformers, a deep learning architecture that learns word relationships through self-attention. We’ll build a basic transformer-based model to understand how to build a large language model from scratch. The goal of our language model will be to predict the next word.

Here are the six main components we’ll cover:

    1. Tokenization
    2. Embedding Layer
    3. Positional Encoding
    4. Self-Attention
    5. Transformer Block
    6. Full Language Model

### Step 1: Tokenization
Computers can’t understand words directly, so we map each word to a unique number (ID). This process is called tokenization. Here’s how to tokenize text:

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
import math

def tokenize(text, vocab):
    return [vocab.get(word, vocab["<UNK>"]) for word in text.split()]

Here’s how this works:

    text.split(): Splits a sentence into words (e.g., “hello world”: [“hello”, “world”]).
    vocab: A dictionary that assigns numbers to words (e.g., {“hello”: 0, “world”: 1, “<UNK>”: 2}).
    vocab.get(word, vocab[“<UNK>”]): Returns a word’s assigned number. If it’s missing, assigns <UNK> (unknown).
    
Think of this as giving each word an ID, so the model can work with numbers instead of text.

### Step 2: Embedding Layer
Numbers alone (like 0 and 1) don’t carry meaning. An embedding layer transforms these numbers into vectors (lists of numbers), allowing words with similar meanings to have similar representations. Here’s how to implement it:

In [3]:
class Embedding(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(Embedding, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

    def forward(self, x):
        return self.embedding(x)

Here’s how the embedding layer works:

    nn.Embedding(vocab_size, embedding_dim): Creates a table where each word ID maps to a vector.
    embedding_dim: Defines the length of each vector (e.g., 16 numbers per word).                                                     
Think of embeddings as assigning each word a personality, so words like happy and joyful get similar vectors.

### Step 3: Positional Encoding
Transformers process all words at once, so they don’t naturally understand order (e.g., “I love you” ≠ “You love I”). Positional encoding fixes this by adding a unique “position signal” to each word. Here’s how to implement positional encoding:

In [4]:
class PositionalEncoding(nn.Module):
    def __init__(self, embedding_dim, max_seq_len=5000):
        super(PositionalEncoding, self).__init__()
        self.embedding_dim = embedding_dim
        pe = torch.zeros(max_seq_len, embedding_dim)
        position = torch.arange(0, max_seq_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, embedding_dim, 2).float() * (-math.log(10000.0) / embedding_dim))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0).transpose(0, 1)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:x.size(0), :]

Here’s how the above function works:

    1. embedding_dim: Matches the vector size from the embedding layer.
    2. max_seq_len: The longest sentence we’ll handle (e.g., 5000 words).
    3. Math (sine and cosine): Creates a pattern of numbers that change based on position (e.g., word 1 gets one pattern, word 2 gets another).
    4. forward: Adds these position numbers to the word vectors.
Think of this as tagging each word with a position stamp so the model understands word order.

### Step 4: Self-Attention
Self-attention helps the model focus on important words. For example, in “The cat sat on the mat”, “sat” relates more to “cat” than “mat”. Here’s how to implement it:

In [5]:
class SelfAttention(nn.Module):
    def __init__(self, embedding_dim):
        super(SelfAttention, self).__init__()
        self.query = nn.Linear(embedding_dim, embedding_dim)
        self.key = nn.Linear(embedding_dim, embedding_dim)
        self.value = nn.Linear(embedding_dim, embedding_dim)

    def forward(self, x):
        queries = self.query(x)
        keys = self.key(x)
        values = self.value(x)
        scores = torch.bmm(queries, keys.transpose(1, 2)) / torch.sqrt(torch.tensor(x.size(-1), dtype=torch.float32))
        attention_weights = torch.softmax(scores, dim=-1)
        attended_values = torch.bmm(attention_weights, values)
        return attended_values

Here’s how self-attention works:

    1. query, key, value: Three transformations of the input vectors. Think of them as asking “What do I care about?” (query), “What’s available?” (key), and “What do I take?” (value).
    2. scores: Measures how much each word relates to every other word.
    3. attention_weights: Turns scores into probabilities (e.g., 70% focus on “how”, 30% on “are”).
    4. attended_values: Combines the important parts of the sentence.
Think of self-attention as a smart highlighter that finds important words to focus on.

### Step 5: Transformer Block
A single attention layer isn’t enough. Transformer blocks combine attention with deeper processing. Here’s how to implement a transformer block:

In [6]:
class TransformerBlock(nn.Module):
    def __init__(self, embedding_dim, hidden_dim):
        super(TransformerBlock, self).__init__()
        self.attention = SelfAttention(embedding_dim)
        self.feed_forward = nn.Sequential(
            nn.Linear(embedding_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, embedding_dim)
        )
        self.norm1 = nn.LayerNorm(embedding_dim)
        self.norm2 = nn.LayerNorm(embedding_dim)

    def forward(self, x):
        attended = self.attention(x)
        x = self.norm1(x + attended)
        forwarded = self.feed_forward(x)
        x = self.norm2(x + forwarded)
        return x

Here’s how the transformer block works:

    1. attention: The self-attention we just built.
    2. feed_forward: A small neural network to process each word further.
    3. norm1, norm2: Normalizes the numbers so they don’t get too big or small (like keeping everyone on the same scale).
    4. x + attended: Adds the original input to the attention output (a trick called “residual connection”).
This is like a brain cell, it listens (attention), thinks (feed-forward), and keeps things stable (normalization).

### Step 6: Full Language Model
Now, we will combine all the pieces into one model that predicts the next word:

In [7]:
class SimpleLLM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_layers):
        super(SimpleLLM, self).__init__()
        self.embedding = Embedding(vocab_size, embedding_dim)
        self.positional_encoding = PositionalEncoding(embedding_dim)
        self.transformer_blocks = nn.Sequential(*[TransformerBlock(embedding_dim, hidden_dim) for _ in range(num_layers)])
        self.output = nn.Linear(embedding_dim, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        x = x.transpose(0, 1) # Transpose for positional encoding
        x = self.positional_encoding(x)
        x = x.transpose(0, 1) # Transpose back
        x = self.transformer_blocks(x)
        x = self.output(x)
        return x

Some key components you should know:

    num_layers: How many transformer blocks to stack (more layers = deeper thinking).
    output: Turns the final vectors back into word predictions (e.g., probabilities for each word in the vocab).
This is the final system, it reads the sentence, understands it, and guesses the next word.

### Step 7: Training the Model
Now, we will teach the model by showing it examples and correcting its mistakes:

In [8]:
vocab = {"hello": 0, "world": 1, "how": 2, "are": 3, "you": 4, "<UNK>": 5}
vocab_size = len(vocab)
embedding_dim = 16
hidden_dim = 32
num_layers = 2

model = SimpleLLM(vocab_size, embedding_dim, hidden_dim, num_layers)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

data = ["hello world how are you", "how are you hello world"]
tokenized_data = [tokenize(sentence, vocab) for sentence in data]

for epoch in range(100):
    for sentence in tokenized_data:
        for i in range(1, len(sentence)):
            input_seq = torch.tensor(sentence[:i]).unsqueeze(0)
            target = torch.tensor(sentence[i]).unsqueeze(0)
            optimizer.zero_grad()
            output = model(input_seq)
            loss = criterion(output[:, -1, :], target)
            loss.backward()
            optimizer.step()
    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 1.9168143272399902
Epoch 10, Loss: 0.764036238193512
Epoch 20, Loss: 0.30136770009994507
Epoch 30, Loss: 0.16430115699768066
Epoch 40, Loss: 0.10447289794683456
Epoch 50, Loss: 0.07189079374074936
Epoch 60, Loss: 0.05206482484936714
Epoch 70, Loss: 0.039196375757455826
Epoch 80, Loss: 0.030427351593971252
Epoch 90, Loss: 0.024214940145611763


Some key components you should know:

    1. input_seq: The words so far (e.g., [0, 1] for “hello world”).
    2. target: The next word (e.g., 2 for “how”).
    3. loss: How far off the prediction was.
    4. optimizer.step(): Updates the model to improve.

### Step 8: Using the Model
Now, let’s predict the next word using our model:

In [9]:
input_text = "hello world how"
input_tokens = tokenize(input_text, vocab)
input_tensor = torch.tensor(input_tokens).unsqueeze(0)
output = model(input_tensor)
predicted_token = torch.argmax(output[:, -1, :]).item()
print(f"Input: {input_text}, Predicted: {list(vocab.keys())[list(vocab.values()).index(predicted_token)]}")

Input: hello world how, Predicted: are


How to Build an Actual LLM with this?
To scale up this model into a practical LLM, several key changes are needed. First, the vocabulary size must expand from just 6 words to 50,000+ words or subwords using techniques like Byte-Pair Encoding (BPE) and tokenizers from libraries like Hugging Face. Instead of two sentences, real-world training requires millions of sentences sourced from books, Wikipedia, or large datasets.

The embedding dimension should increase from 16 to 512 or 1024 for richer word representations, while the hidden dimension should grow from 32 to at least 2048 for greater processing power. The number of transformer layers needs to scale from 2 to 12–96, similar to models like GPT-3. Instead of simple self-attention, multi-head attention should be implemented using nn.MultiheadAttention for better contextual understanding. Training also becomes significantly more complex, moving from 100 CPU epochs to multi-GPU/TPU training over days or weeks, requiring optimizations like batching (DataLoader), gradient clipping, and learning rate schedulers.

Hardware-wise, a real LLM demands multiple high-end GPUs (e.g., 8+ A100s) and frameworks like PyTorch Lightning or DeepSpeed for efficient scaling.

# Example 2: Building an AI Agent using GenAI API

With the rise of large language models like GPT-4o, building intelligent AI agents has never been more accessible. Using the GenAI or any other AI API like Open AI, Grok, etc, we can create agents that understand context, reason through information, and respond naturally to user queries. In this example, we’ll focus on building an AI Agent using the GenAI API to intelligently process structured data and deliver accurate, conversational answers.

Here, we will be building an AI Agent that will:

    1. Understand the data context
    2. Accept user queries in natural language
    3. Use GenAI GPT models to analyze and respond intelligently.
    
But, to get started with this task, make sure you sign up for the GenAI. Here are the steps you can follow:

    1. Go to Google AI studio platform and sign up or log in.
    2. Navigate to the API Keys section.
    3. Click on Create New Secret Key and copy it.
    4. Use it safely inside your Python code.   
    5. pip install -q -U google-genai
Once you get your API, you can use it like this:

In [1]:
from google import genai

client = genai.Client(api_key='AIzaSyD9gKtAPMHIdP81UtLVrwDRHWnG5-zvxc8')

def ai_agent(user_query, df):
    data_context = create_data_summary(df)

    prompt = f"""
                You are a data expert AI agent.
                
                You have been provided with this dataset summary:
                {data_context}
                
                Now, based on the user's question:
                '{user_query}'
                
                Think step-by-step. Assume you can access and analyze the dataset like a Data Scientist would using Pandas.
                
                Give a clear, final answer.
                """
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    
    return response.text


### Importing the Data
Now, we will import a dataset based on loan applications. We will use this data to build an AI Agent that can answer questions based on loan approvals.
You can download the dataset from https://drive.google.com/file/d/1LIvIdqdHDFEGnfzIgEh4L6GFirzsE3US/view

In [2]:
import pandas as pd

df = pd.read_csv('Datasets\\Loan-Approval-Prediction.csv')
df.dropna().head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y


In [3]:
# Now, we will create a function to summarize the data:
def create_data_summary(df):
    summary = f"The dataset has {df.shape[0]} rows and {df.shape[1]} columns.\n"
    summary += "Columns:\n"
    for col in df.columns:
        summary += f"- {col} (type: {df[col].dtype})\n"
    return summary

This summary will help the agent understand the structure without actually loading the entire data into the prompt (which would exceed token limits).

### Building the AI Agent Function
Now, let’s define the AI Agent that will handle user queries based on the data summary:

Here, we defined a function ai_agent that takes a user query and the dataset, summarizes the dataset structure, and creates a prompt combining both the context and the question. This prompt is then sent to OpenAI’s GPT-4o model using the client.chat.completions.create() method, and the model’s step-by-step, natural-language response is returned to the user.

### Create an interactive loop for user's question
Now, we will create an interactive loop where users can ask questions to the AI Agent:

In [6]:
print("""
    Welcome to Loan Review AI Agent!
    You can ask anything about the loan applicants data.
    Type 'exit' to quit.
    """)

while True:
    user_input = input("\nYour question: ")
    if user_input.lower() == "exit":
        break
    response = ai_agent(user_input, df)
    print("\nAI Agent Response:")
    print(response)

# What is the average loan amount applied for by all applicants?
# Who has the highest applicant income?
# How many applicants are self-employed?


    Welcome to Loan Review AI Agent!
    You can ask anything about the loan applicants data.
    Type 'exit' to quit.
    



Your question:  exit


# Example 3: Document Analysis using LLMs with Python

Document analysis refers to extracting, interpreting, and understanding the information contained within a document. Traditionally, this involved manual review or simple keyword-based techniques, but with the rise of Large Language Models (LLMs) like GPT and BERT, LLMs are now preferred for document analysis because they can comprehend context, generate summaries, answer questions, and identify key insights efficiently.

For the task of document analysis using LLMs, I’ll be using a document that contains the terms of the services offered by Google.
This can be downloaded from https://www.scribd.com/document/727624966/Google-Terms-of-Service-En

### Step 1: Extract Text from the PDF
The first step in document analysis is extracting the content from a PDF file. We can use libraries like pdfplumber to open and read the text from each page of the PDF and save it into a .txt file for further analysis. You can install pdfplumber on your Python environment using the command: pip install pdfplumber. Here’s how to extract text from the PDF:

In [16]:
import pdfplumber

pdf_path = "Datasets\\google_terms_of_service_en_in.pdf"

output_text_file = "extracted_text.txt"

with pdfplumber.open(pdf_path) as pdf:
    extracted_text = ""
    for page in pdf.pages:
        extracted_text += page.extract_text()

with open(output_text_file, "w") as text_file:
    text_file.write(extracted_text)

print(f"Text extracted and saved to {output_text_file}")

Could get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could get FontBBox from font descriptor because None cannot be parsed as 4 floats


Text extracted and saved to extracted_text.txt


The extracted text is stored in the variable extracted_text, which is then saved to a file for later use.

### Step 2: Preview the Extracted Text
After extracting the text, it’s essential to preview the content to ensure everything is correctly captured. This allows you to check for any formatting issues or missing content:

In [17]:
# reading pdf content
with open("extracted_text.txt", "r") as file:
    document_text = file.read()

# preview the document content
print(document_text[:500])  # preview the first 500 characters

GOOGLE TERMS OF SERVICE
Effective May 22, 2024 | Archived versions
What’s covered in these terms
We know it’s tempting to skip these Terms of
Service, but it’s important to establish what you
can expect from us as you use Google services,
and what we expect from you.
These Terms of Service re ect the way Google’s business works, the laws that apply to
our company, and certain things we’ve always believed to be true. As a result, these Terms
of Service help de ne Google’s relationship with you as


### Step 3: Summarize the Document
To get a high-level overview of the document, you can use a pre-trained summarization model like t5-small. This allows you to condense large pieces of text into shorter summaries, which helps you to grasp the most important information. Here’s how to summarize the document:

In [34]:
from transformers import pipeline

# load the summarization pipeline
summarizer = pipeline("summarization", model="t5-small")

# summarize the document text (you can summarize parts if the document is too large)
summary = summarizer(document_text[:10000], max_length=150, min_length=30, do_sample=False)
print("Summary:", summary[0]['summary_text'])

Device set to use cpu
Token indices sequence length is longer than the specified maximum sequence length for this model (2048 > 512). Running this sequence through the model will result in indexing errors
Both `max_new_tokens` (=256) and `max_length`(=150) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Summary: these Terms of Service reect the way Google’s business works, the laws that apply to our company, and certain things we’ve always believed to be true . these terms help dene the relationship between you and Google . if you’re under the age required to manage your own Google Account, you must have your parent or legal guardian’s permission to use a Google Account .


The pipeline(“summarization”, model= “t5-small”) sets up the summarization model using T5-small, a pre-trained transformer model designed for text summarization. The document_text[:1000] specifies the portion of the text to summarize (the first 1000 characters), while max_length = 150 and min_length = 30 control the maximum and minimum length of the summary in tokens. The do_sample = False parameter ensures deterministic output, meaning the model will not randomly sample from possible summaries but will give the same result every time.

### Step 4: Split the Document into Sentences and Passages
For more detailed analysis, like question generation, it’s important to split the document into smaller chunks. This step tokenizes the document into sentences and combines them into manageable passages for subsequent steps. Here’s how to split the document into sentences and passages:

In [36]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

# split text into sentences
sentences = sent_tokenize(document_text)

# combine sentences into passages
passages = []
current_passage = ""
for sentence in sentences:
    if len(current_passage.split()) + len(sentence.split()) < 200:  # adjust the word limit as needed
        current_passage += " " + sentence
    else:
        passages.append(current_passage.strip())
        current_passage = sentence
if current_passage:
    passages.append(current_passage.strip())

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In this part of the code, we are using the NLTK library to split the extracted document text into individual sentences using the sent_tokenize() function. Then, we combine these sentences into manageable passages by setting a word limit of 200 words for each passage. This helps ensure that each passage is of a suitable length for further processing by language models, which often have token limits. If the current passage exceeds the word limit, it is appended to the passages list, and the process continues until all sentences are grouped into passages.

### Step 5: Generate Questions from the Passages Using LLMs
The next step is to generate questions based on the document’s content. This helps in understanding key information points and can be used to check the comprehension of the document. Here’s how to generate questions from passages using LLMs:

In [51]:
# load the question generation pipeline
# qg_pipeline = pipeline(
#     "text2text-generation",
#     model="valhalla/t5-base-qg-hl",
#     tokenizer="valhalla/t5-base-qg-hl",
#     framework="pt",
#     trust_remote_code=True
# )
qg_pipeline = pipeline(
    "text2text-generation",
    model="t5-small",  # has TensorFlow weights
    tokenizer="t5-small"
)
# function to generate questions using the pipeline
def generate_questions_pipeline(passage, min_questions=3):
    input_text = f"generate questions: {passage}"
    results = qg_pipeline(input_text)
    questions = results[0]['generated_text'].split('<sep>')
    
    # ensure we have at least 3 questions
    questions = [q.strip() for q in questions if q.strip()]
    
    # if fewer than 3 questions, try to regenerate from smaller parts of the passage
    if len(questions) < min_questions:
        passage_sentences = passage.split('. ')
        for i in range(len(passage_sentences)):
            if len(questions) >= min_questions:
                break
            additional_input = ' '.join(passage_sentences[i:i+2])
            additional_results = qg_pipeline(f"generate questions: {additional_input}")
            additional_questions = additional_results[0]['generated_text'].split('<sep>')
            questions.extend([q.strip() for q in additional_questions if q.strip()])
    
    return questions[:min_questions]  # return only the top 3 questions

# generate questions from passages
for idx, passage in enumerate(passages):
    questions = generate_questions_pipeline(passage)
    print(f"Passage {idx+1}:\n{passage}\n")
    print("Generated Questions:")
    for q in questions:
        print(f"- {q}")
    print(f"\n{'-'*50}\n")

Device set to use cpu


Passage 1:
GOOGLE TERMS OF SERVICE
Effective May 22, 2024 | Archived versions
What’s covered in these terms
We know it’s tempting to skip these Terms of
Service, but it’s important to establish what you
can expect from us as you use Google services,
and what we expect from you. These Terms of Service re ect the way Google’s business works, the laws that apply to
our company, and certain things we’ve always believed to be true. As a result, these Terms
of Service help de ne Google’s relationship with you as you interact with our services. For
example, these terms include the following topic headings:
What you can expect from us, which describes how we provide and develop our
services
What we expect from you, which establishes certain rules for using our services
Content in Google services, which describes the intellectual property rights to the
content you  nd in our services — whether that content belongs to you, Google, or
others
In case of problems or disagreements, which describes o

In this part of the code, we are using a question generation model (T5-based model valhalla/t5-base-qg-hl) from the Hugging Face transformers library to automatically generate questions from text passages. The function generate_questions_pipeline() takes a text passage as input and produces a list of questions. We generate at least three questions for each passage, and if not, we split the passage into smaller parts and generate additional questions. This approach guarantees comprehensive question generation for each passage, and we print the questions along with the corresponding passage for review. Below is the output for the passage 1:

### Step 6: Answer the Generated Questions Using a QA Model
After generating the questions, we can use a pre-trained question-answering (QA) model to find the answers within the text. The deepset/roberta-base-squad2 model extracts answers based on the context of the passage. Here’s how to answer the generated questions:

In [52]:
# load the QA pipeline
qa_pipeline = pipeline("question-answering", model="deepset/roberta-base-squad2")

# function to track and answer only unique questions
def answer_unique_questions(passages, qa_pipeline):
    answered_questions = set()  # to store unique questions

    for idx, passage in enumerate(passages):
        questions = generate_questions_pipeline(passage)

        for question in questions:
            if question not in answered_questions:  # check if the question has already been answered
                answer = qa_pipeline({'question': question, 'context': passage})
                print(f"Q: {question}")
                print(f"A: {answer['answer']}\n")
                answered_questions.add(question)  # add the question to the set to avoid repetition
        print(f"{'='*50}\n")
              
answer_unique_questions(passages, qa_pipeline)

Device set to use cpu
C:\Users\HP\anaconda3\Lib\site-packages\transformers\pipelines\question_answering.py:390: FutureWarning: Passing a list of SQuAD examples to the pipeline is deprecated and will be removed in v5. Inputs should be passed using the `question` and `context` keyword arguments instead.
  warnings.warn(


Q: Terms of Service Effective May 22, 2024 | Archived versions What’s covered in these terms We know it’s tempting skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google services . These Terms of Service reect the way Google’s business works, the laws that apply to our company, and certain things we’ve always believed true . These Terms of Service reect the way Google’s business works, the laws that apply to our
A: GOOGLE

Q: Archived versions What’s covered in these terms We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google services, and what we expect from you These Terms of Service reect the way Google’s business works, the laws that apply to our company, and certain things we’ve always believed to be true We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as
A: GOOGLE TERMS OF SERVICE

Q: Di

In this part of the code, we used a question-answering (QA) pipeline with the deepset/roberta-base-squad2 model to answer questions generated from the document passages. The function answer_unique_questions() tracks unique questions in a set to ensure it answers each question only once. As the code processes each passage, it checks whether it has already answered a question; if not, it generates an answer based on the passage’s context. This avoids answering duplicate questions and ensures efficient processing of all relevant queries. Above is the output for the passage 1:

# Examples 4: Building a RAG Pipeline for LLMs

Large Language Models (LLMs) are powerful, but they have a major limitation: their knowledge is static and limited to the data they were trained on. This is where Retrieval-Augmented Generation (RAG) comes in. So, if you want to learn how to enhance LLMs by retrieving relevant external knowledge before generating responses, this article is for you. In this example, I’ll take you through building a RAG Pipeline for LLMs using Hugging Face Transformers and Python.

### So, What is a RAG Pipeline?
A Retrieval-Augmented Generation (RAG) pipeline consists of two key components:

Retriever: Searches a knowledge base for relevant documents based on the user’s query.

Generator: Uses retrieved documents as context to generate accurate and relevant responses.
RAG improves LLMs by reducing hallucinations through real-world context, ensuring responses are more accurate and grounded in factual information. It also keeps answers up-to-date by retrieving the latest knowledge, eliminating the need for frequent retraining. Additionally, by incorporating external data sources, RAG significantly enhances the factual accuracy of AI-generated responses, which makes LLMs more reliable and context-aware.

In our implementation, we will:

    Use Wikipedia as our external knowledge source.
    Employ Sentence Transformers for embedding text and FAISS for efficient similarity search.
    Utilize Hugging Face’s question-answering pipeline to extract answers from retrieved documents.
Let’s import the necessary Python libraries to get started: pip install faiss-cpu, sentenceTransformer

In [55]:
import wikipedia
from transformers import AutoTokenizer, AutoModelForQuestionAnswering, pipeline
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

### Step 1: Retrieving Knowledge
To simulate an external knowledge base, we’ll fetch relevant Wikipedia articles based on a given topic:

In [56]:
def get_wikipedia_content(topic):
    try:
        page = wikipedia.page(topic)
        return page.content
    except wikipedia.exceptions.PageError:
        return None
    except wikipedia.exceptions.DisambiguationError as e:
        # handle cases where the topic is ambiguous
        print(f"Ambiguous topic. Please be more specific. Options: {e.options}")
        return None

# user input
topic = input("Enter a topic to learn about: ")
document = get_wikipedia_content(topic)

if not document:
    print("Could not retrieve information.")
    exit()

# question: Apple Computers

Enter a topic to learn about:  what is data analysis


Here, we are retrieving Wikipedia content based on a user-provided topic using the Wikipedia API. If the topic is valid, the function returns the page content; otherwise, it handles errors by either notifying the user of an ambiguous topic with multiple options or exiting if no relevant page is found.

Since Wikipedia articles can be long, we will split the text into smaller overlapping chunks for better retrieval:m

In [57]:
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-mpnet-base-v2")

def split_text(text, chunk_size=256, chunk_overlap=20):
    tokens = tokenizer.tokenize(text)
    chunks = []
    start = 0
    while start < len(tokens):
        end = min(start + chunk_size, len(tokens))
        chunks.append(tokenizer.convert_tokens_to_string(tokens[start:end]))
        if end == len(tokens):
            break
        start = end - chunk_overlap
    return chunks

chunks = split_text(document)
print(f"Number of chunks: {len(chunks)}")

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (6115 > 512). Running this sequence through the model will result in indexing errors


Number of chunks: 26


Here, we are tokenizing the retrieved Wikipedia content and splitting it into smaller overlapping chunks for efficient retrieval. We used a pre-trained tokenizer (all-mpnet-base-v2) to break the text into tokens, then divided it into fixed-size segments (256 tokens each) with an overlap of 20 tokens to maintain context between chunks.

### Step 2: Storing and Retrieving Knowledge
To efficiently search for relevant chunks, we will use Sentence Transformers to convert text into embeddings and store them in a FAISS index:

In [58]:
embedding_model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")
embeddings = embedding_model.encode(chunks)

dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings))

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Here, we converted the text chunks into numerical embeddings using the Sentence Transformer model (all-mpnet-base-v2), which captures their semantic meaning. We then created a FAISS index with an L2 (Euclidean) distance metric and stored the embeddings in it. This will allow us to efficiently retrieve the most relevant chunks based on a user’s query.

### Step 3: Querying the RAG Pipeline
Now, we will take user input for the RAG pipeline. When a user asks a question, we will:

    Convert the query into an embedding.
    Retrieve the top-k most relevant chunks using FAISS.
    Use an LLM-powered question-answering model to generate the answer.

In [59]:
query = input("Ask a question about the topic: ")
query_embedding = embedding_model.encode([query])

k = 3
distances, indices = index.search(np.array(query_embedding), k)
retrieved_chunks = [chunks[i] for i in indices[0]]
print("Retrieved chunks:")
for chunk in retrieved_chunks:
    print("- " + chunk)

# question example: Legal Cases Against Apple Computers

Ask a question about the topic:  why analysis


Retrieved chunks:
- . all of the above are varieties of data analysis. = = data analysis process = = data analysis is a process for obtaining raw data, and subsequently converting it into information useful for decision - making by users. statistician john tukey, defined data analysis in 1961, as : " procedures for analyzing data, techniques for interpreting the results of such procedures, ways of planning the gathering of data to make its analysis easier, more precise or more accurate, and all the machinery and results of ( mathematical ) statistics which apply to analyzing data. " there are several phases, and they are iterative, in that feedback from later phases may result in additional work in earlier phases. = = = data requirements = = = the data is necessary as inputs to the analysis, which is specified based upon the requirements of those directing the analytics ( or customers, who will use the finished product of the analysis ). the general type of entity upon which the data w

### Step 4: Answering the Question with an LLM
Now, we will use a pre-trained question-answering model to extract the final answer from the retrieved context:

In [60]:
qa_model_name = "deepset/roberta-base-squad2"
qa_tokenizer = AutoTokenizer.from_pretrained(qa_model_name)
qa_model = AutoModelForQuestionAnswering.from_pretrained(qa_model_name)
qa_pipeline = pipeline("question-answering", model=qa_model, tokenizer=qa_tokenizer)

context = " ".join(retrieved_chunks)
answer = qa_pipeline(question=query, context=context)
print(f"Answer: {answer['answer']}")

Device set to use cpu


Answer: discovering useful information, informing conclusions, and supporting decision - making


So, this is how you now have a fully functional RAG pipeline for LLMs that can be used in real-world AI applications.

# Example 5: AI Image Caption Recommendation System

I will build an AI Image Caption Recommendation System using a retrieval-based approach, leveraging CLIP (Contrastive Language–Image Pre-training) for both image and text understanding.

First, the input image will be preprocessed and fed into the CLIP image encoder to generate a high-dimensional feature vector representing the image’s visual content. A similar process will be applied to a set of candidate captions, using the CLIP text encoder to generate text embeddings for each caption. Next, the cosine similarity between the image embedding and each caption embedding will be calculated. This similarity score will quantify how well each caption aligns with the visual content of the image.

Finally, the system ranks the candidate captions based on their similarity scores and presents the top-ranked captions as recommendations.

In [2]:
# Importing the necessary Python libraries:
import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel, AutoProcessor, AutoModelForCausalLM

### Now, let’s write a Python function for handling the loading and preprocessing of an image:

In [3]:
# image loading and preprocessing

def load_and_preprocess_image(image_path):
    image = Image.open(image_path).convert("RGB")
    processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
    inputs = processor(images=image, return_tensors="pt")
    return inputs, processor

This function opens the image using PIL, converts it to RGB format (important for consistency), and then uses the CLIPProcessor to transform the image into a format suitable for the CLIP model. The processor handles resizing, normalization, and other necessary transformations. The output will be a PyTorch tensor ready for CLIP.

### Generating Image Embeddings
Now, we will write a function to generate image embeddings using CLIP. CLIP is a multi-modal model which leverages the power of LLMs, which can understand the content of images and match them to their relevant textual descriptions. Let’s write the function to generate image embeddings:

In [4]:
# image understanding with CLIP
def generate_image_embeddings(inputs):
    model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
    with torch.no_grad():
        image_features = model.get_image_features(**inputs)

    return image_features, model

This function loads the pre-trained CLIP model. The crucial step here is model.get_image_features(**inputs), which passes the preprocessed image tensor to the CLIP model and extracts a high-dimensional feature vector representing the image’s visual content. torch.no_grad() is used to prevent gradient calculations during inference, saving memory and speeding up the process.

### Matching Image with Text Embeddings
Now, we will write a function to match captions:

In [5]:
# caption matching (using CLIP text embeddings)
def match_captions(image_features, captions, clip_model, processor):
    # 1. get text embeddings for the captions:
    text_inputs = processor(text=captions, return_tensors="pt", padding=True)
    with torch.no_grad():
        text_features = clip_model.get_text_features(**text_inputs)

    # 2. calculate cosine similarity between image and text features:
    image_features = image_features.detach().cpu().numpy()
    text_features = text_features.detach().cpu().numpy()

    similarities = cosine_similarity(image_features, text_features)

    # 3. find the best matching captions:
    best_indices = similarities.argsort(axis=1)[0][::-1]  
    best_captions = [captions[i] for i in best_indices]

    return best_captions, similarities[0][best_indices].tolist()

This function takes the image features and a list of candidate captions as input. It processes the captions using the same CLIPProcessor (now for text) to get text embeddings. It then calculates the cosine similarity between the image embedding and each text embedding. Cosine similarity measures the angle between two vectors; a value closer to 1 indicates higher similarity. The function will return the captions ranked by similarity and their corresponding similarity scores.

Now, let’s write the driver function:

In [6]:
# main function
def image_captioning(image_path, candidate_captions):  
    inputs, processor = load_and_preprocess_image(image_path)
    image_features, clip_model = generate_image_embeddings(inputs)

    best_captions, similarities = match_captions(image_features, candidate_captions, clip_model, processor)
    return best_captions, similarities

This function ties together the preprocessing, feature extraction, and matching processes. It takes an image path and a list of candidate captions, processes the image, gets its features, and then matches these features against the captions. The result will be a list of best-fit captions with their similarity scores.

Now, let’s write a list of captions that we can use to match with the image:

In [7]:
candidate_captions = [
    "Trees, Travel and Tea!", "A refreshing beverage.", "A moment of indulgence.", "The perfect thirst quencher.", 
    "Your daily dose of delight.", "Taste the tradition.", "Savor the flavor.", "Refresh and rejuvenate.", "Unwind and enjoy.",
    "The taste of home.", "A treat for your senses.", "A taste of adventure.", "A moment of bliss.", "Your travel companion.",
    "Fuel for your journey.", "The essence of nature.", "The warmth of comfort.", "A sip of happiness.", "Pure indulgence.",
    "Quench your thirst, ignite your spirit.", "Awaken your senses, embrace the moment.", "The taste of faraway lands.",
    "A taste of home, wherever you are.", "Your daily dose of delight.", "Your moment of serenity.", "The perfect pick-me-up.",
    "The perfect way to unwind.", "Taste the difference.", "Experience the difference.", "A refreshing escape.", "A delightful escape.",
    "The taste of tradition, the spirit of adventure.", "The warmth of home, the joy of discovery.", "Your passport to flavor.",
    "Your ticket to tranquility.", "Sip, savor, and explore.", "Indulge, relax, and rejuvenate.", "The taste of wanderlust.",
    "The comfort of home.", "A journey for your taste buds.", "A haven for your senses.", "Your refreshing companion.",
    "Your delightful escape.", "Taste the world, one sip at a time.", "Embrace the moment, one cup at a time.", "The essence of exploration.",
    "The comfort of connection.", "Quench your thirst for adventure.", "Savor the moment of peace.", "The taste of discovery.",
    "The warmth of belonging.", "Your travel companion, your daily delight.", "Your moment of peace, your daily indulgence.",
    "The spirit of exploration, the comfort of home.",
    "The joy of discovery, the warmth of connection.", "Sip, savor, and set off on an adventure.", "Indulge, relax, and find your peace.",
    "A delightful beverage.", "A moment of relaxation.", "The perfect way to start your day.", "The perfect way to end your day.",
    "A treat for yourself.", "Something to savor.", "A moment of calm.", "A taste of something special.", "A refreshing pick-me-up.",
    "A comforting drink.", "A taste of adventure.", "A moment of peace.", "A small indulgence.", "A daily ritual.", "A way to connect with others.",
    "A way to connect with yourself.", "A taste of home.", "A taste of something new.", "A moment to enjoy.", "A moment to remember."
]

The quality and diversity of these captions will significantly impact the system’s performance.

### Let’s Test by Finding Captions
Now, I will take an image as input and use our AI Image Recommendation System to find the best captions for the image. Below is the image I am using:

<img src="Notebook images/download (136).png" alt="Drawing" style="width: 300px;"/>

Now, let’s find the most relevant captions for the image:

In [8]:
from sklearn.metrics.pairwise import cosine_similarity 

best_captions, similarities = image_captioning("Notebook images/download (136).png", candidate_captions)

# get the top 5 results
top_n = min(5, len(best_captions))
top_best_captions = best_captions[:top_n]
top_similarities = similarities[:top_n]

print("Top 5 Best Captions:")
for i, (caption, similarity) in enumerate(zip(top_best_captions, top_similarities)):
    print(f"{i+1}. {caption} (Similarity: {similarity:.4f})")

Top 5 Best Captions:
1. Your moment of peace, your daily indulgence. (Similarity: 0.2538)
2. Embrace the moment, one cup at a time. (Similarity: 0.2515)
3. Taste the world, one sip at a time. (Similarity: 0.2495)
4. Unwind and enjoy. (Similarity: 0.2487)
5. Savor the moment of peace. (Similarity: 0.2486)


This is how to use the image_captioning function with an image path and the list of candidate captions. As you can see, it then prints the top 5 best captions along with their similarity scores. This caption recommendation system doesn’t describe the image that an LLM will do. It recommends a relevant caption from a list of captions that you can use on social media platforms.

# Example 6: How to Build an AI ChatBot in Python

#### Step 1: Gather the Tools
You need two libraries:

    . ctransformers is your bridge to integrating Mistral 7B, enabling seamless interaction with the model.
    . jupyter_bokeh brings in the power of interactive visualizations, which we’ll use later to create a polished chatbot web interface.

pip install ctransformers

pip install jupyter_bokeh

#### Step 2: Bring the Brain to Life
With the tools in hand, it's time to load the Mistral 7B model. Think of this step as waking up your chatbot’s brain. Here’s how:

    . AutoModelForCausalLM.from_pretrained: This command loads the Mistral 7B model. You’ll need the correct model file (mistral-7b-instruct-v0.1.Q4_K_M.gguf).
    
    . gpu_layers: If you’re using a GPU, set this to 50 for faster performance. If not, set it to 0.
    
    . response: Your first interaction with the chatbot. Try a prompt like “AI is going to” and watch the model complete the sentence.

At this point, you’ve brought the chatbot’s brain to life—it can process prompts and generate coherent responses.

In [ ]:
# With the tools in hand, it's time to load the Mistral 7B model. Think of this step as waking up your chatbot’s brain. Here’s how:
# For pc with low memory use this instead (lightest, lower quality, ~2–3 GB): mistral-7b-instruct-v0.1.Q2_K.gguf 

from ctransformers import AutoModelForCausalLM

llm = AutoModelForCausalLM.from_pretrained(

    "TheBloke/Mistral-7B-Instruct-v0.1-GGUF",

    model_file="mistral-7b-instruct-v0.1.Q4_K_M.gguf", 

    model_type="mistral",

    gpu_layers=0  # Adjust to 0 if running without GPU

)


Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

#### Step 3: Train Your ChatBot- Teach It to Listen
A chatbot isn’t just about generating text; it needs to listen to what users say and respond in real time. This is where asynchronous input handling comes in.

    . callback(contents: str) function acts as the ears of your chatbot. It listens to user inputs (e.g., questions or prompts).
    
    . yield message: As the chatbot processes the input, it sends back token-by-token responses, creating a dynamic and conversational experience.

Run this asynchronously, and your chatbot will now listen like a pro.

In [ ]:
from ctransformers import AutoModelForCausalLM

async def callback(contents: str):

    llms = {}

    if "mistral" not in llms:

        llms["mistral"] = AutoModelForCausalLM.from_pretrained(

            "TheBloke/Mistral-7B-Instruct-v0.1-GGUF",

            model_file="mistral-7b-instruct-v0.1.Q4_K_M.gguf",

            gpu_layers=1,

        )

    llm = llms["mistral"]

    response = llm(contents, stream=True, max_new_tokens=1000)

    message = ""

    for token in response:

        message += token

        yield message

#### Step 4: Let It Speak
With input handling in place, it’s time to teach your chatbot to respond effectively. Using a simple loop, you can simulate real-time replies:

    . async for handles the chatbot’s response generation in real time.
    
    . print(value): As each token is generated, it’s displayed immediately, making the interaction feel smooth and natural.

This step completes the chatbot’s ability to listen and respond.

In [ ]:
text = callback("AI is going to")
text

# The code below may hang your system. So please be careful and feel free to comment it.
# notepaasync for value in text:

#   print(value)

#### Step 5: Set up an Interface
Now that your chatbot platform has a brain, ears, and a voice, let’s give it a user-friendly interface. We’ll use Panel, a Python library for creating interactive dashboards and widgets.

Demonstrates how to use the ChatInterface widget to create a chatbot using "Mistral thru CTransformers".

Here’s what’s happening:

    . ChatInterface widget acts as the chatbot’s body, where users can type messages and see responses.
    
    . callback integrates the input and output logic we set up earlier, enabling the chatbot to process messages dynamically.
    
    . chat_interface.servable() launches the interface.

In [ ]:
import panel as pn

from ctransformers import AutoModelForCausalLM

pn.extension()

async def callback(contents: str, user: str, instance: pn.chat.ChatInterface):

    if "mistral" not in llms:

        instance.placeholder_text = "Downloading model; please wait..."

        llms["mistral"] = AutoModelForCausalLM.from_pretrained(

            "TheBloke/Mistral-7B-Instruct-v0.1-GGUF",

            model_file="mistral-7b-instruct-v0.1.Q4_K_M.gguf",

            gpu_layers=1,

        )

    llm = llms["mistral"]

    response = llm(contents, stream=True, max_new_tokens=1000)

    message = ""

    for token in response:

        message += token

        yield message

llms = {}

chat_interface = pn.chat.ChatInterface(callback=callback, callback_user="Mistral")

chat_interface.send(

    "Send a message to get a reply from Mistral!", user="System", respond=False

)

chat_interface.servable()

# Example 7: Question and Answer system Using Custom Dataset

I'll implement a complete solution for answering questions from an article in a pdf document using a specialized approach that combines Retrieval-Augmented Generation (RAG) with Question Answering.

System Architecture

    Document Processing: Extract and structure the PDF content

    Vector Database: Create searchable embeddings of document chunks
    
    Retrieval: Find relevant document sections for each question
    
    QA Model: Generate answers from retrieved contexts

## Implementation
### 1. Setup Environment: 
First install required packages:

pip install PyPDF2 sentence-transformers faiss-cpu transformers

### 2. Document Processing

In [12]:
import PyPDF2
import re
from typing import List

def extract_text_from_pdf(pdf_path: str) -> str:
    """Extract text from PDF with proper formatting"""
    text = ""
    with open(pdf_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for page in reader.pages:
            text += page.extract_text()
    return text

def clean_text(text: str) -> str:
    """Clean and normalize the extracted text"""
    text = re.sub(r'\s+', ' ', text)  # Replace multiple whitespace
    text = re.sub(r'-\n', '', text)  # Join hyphenated words
    return text.strip()

def chunk_text(text: str, chunk_size: int = 500, overlap: int = 100) -> List[str]:
    """Split document into manageable chunks with overlap"""
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = ' '.join(words[i:i + chunk_size])
        chunks.append(chunk)
    return chunks

# Process the Uganda rating document
document_text = extract_text_from_pdf("Datasets\\google_terms_of_service_en_in.pdf") # You can supply your own custom document here too
cleaned_text = clean_text(document_text)
document_chunks = chunk_text(cleaned_text)

### 3. Create Vector Database

In [13]:
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

class VectorDatabase:
    def __init__(self):
        self.encoder = SentenceTransformer('all-MiniLM-L6-v2')
        self.index = None
        self.chunks = []
        
    def build_index(self, chunks: List[str]):
        self.chunks = chunks
        embeddings = self.encoder.encode(chunks, show_progress_bar=True)
        self.index = faiss.IndexFlatIP(embeddings.shape[1])
        self.index.add(embeddings)
        
    def search(self, query: str, k: int = 3) -> List[str]:
        query_embedding = self.encoder.encode([query])
        distances, indices = self.index.search(query_embedding, k)
        return [self.chunks[i] for i in indices[0]]

# Build our document vector store
vector_db = VectorDatabase()
vector_db.build_index(document_chunks)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

### 4. QA System Implementation

In [14]:
from transformers import pipeline

class SovereignRatingQA:
    def __init__(self):
        self.qa_model = pipeline(
            "question-answering",
            model="deepset/roberta-base-squad2"
        )
        self.vector_db = vector_db
        
    def answer_question(self, question: str) -> dict:
        # Step 1: Retrieve relevant context
        contexts = self.vector_db.search(question)
        
        # Step 2: Get answers from each context
        answers = []
        for context in contexts:
            try:
                result = self.qa_model(question=question, context=context)
                answers.append({
                    "answer": result['answer'],
                    "score": result['score'],
                    "context": context
                })
            except:
                continue
        
        # Step 3: Return best answer
        if not answers:
            return {
                "answer": "I couldn't find an answer in the document.",
                "confidence": 0.0
            }
        
        # Select answer with highest confidence score
        best_answer = max(answers, key=lambda x: x['score'])
        return {
            "answer": best_answer['answer'],
            "confidence": float(best_answer['score']),
            "source_context": best_answer['context']
        }

# Initialize our QA system
qa_system = SovereignRatingQA()

### 5. Test with question

In [15]:
question = "What you can expect from us, which describes how we provide and develop our services?"
response = qa_system.answer_question(question)
print(response['source_context'])

give you permission to access and use our services if you agree to follow these terms, which re ect how Google’s business works and how we earn money. What you can expect from us Provide a broad range of useful services We provide a broad range of services that are subject to these terms, including: apps and sites (like Search and Maps) platforms (like Google Shopping) integrated services (like Maps embedded in other companies’ apps or sites) devices (like Google Nest and Pixel) Many of these services also include content that you can stream or interact with. Our services are designed to work together, making it easier for you to move from one activity to the next. For example, if your Calendar event includes an address, you can click on that address and Maps can show you how to get there. Develop, improve, and update Google services We’re constantly developing new technologies and features to improve our services. For example, we use arti cial intelligence and machine learning to prov